2024-09-22 14:24:27,963 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/Users/levbasalaev/PycharmProjects/Module12/tests_12_4.py", line 22, in test_run
    object2 = rt_with_exceptions.Runner(28, speed=5)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levbasalaev/PycharmProjects/Module12/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-22 14:24:27,965 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "/Users/levbasalaev/PycharmProjects/Module12/tests_12_4.py", line 12, in test_walk
    object1 = rt_with_exceptions.Runner('Nick', speed=-5)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/levbasalaev/PycharmProjects/Module12/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
